/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootloaderPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

void PINMUX_InitSDRAM(void);
void PINMUX_InitPowerSW(void);
void PINMUX_InitKeyboard(void);
void PINMUX_InitCellular(void);
void PINMUX_InitEMMC(void);

#define PINMUX_EMMC_DATA0 IOMUXC_GPIO_SD_B1_03_USDHC2_DATA0
#define PINMUX_EMMC_DATA1 IOMUXC_GPIO_SD_B1_02_USDHC2_DATA1
#define PINMUX_EMMC_DATA2 IOMUXC_GPIO_SD_B1_01_USDHC2_DATA2
#define PINMUX_EMMC_DATA3 IOMUXC_GPIO_SD_B1_00_USDHC2_DATA3
#define PINMUX_EMMC_DATA4 IOMUXC_GPIO_SD_B1_08_USDHC2_DATA4
#define PINMUX_EMMC_DATA5 IOMUXC_GPIO_SD_B1_09_USDHC2_DATA5
#define PINMUX_EMMC_DATA6 IOMUXC_GPIO_SD_B1_10_USDHC2_DATA6
#define PINMUX_EMMC_DATA7 IOMUXC_GPIO_SD_B1_11_USDHC2_DATA7
#define PINMUX_EMMC_CLK   IOMUXC_GPIO_SD_B1_04_USDHC2_CLK
#define PINMUX_EMMC_CMD   IOMUXC_GPIO_SD_B1_05_USDHC2_CMD
#define PINMUX_EMMC_RESET IOMUXC_GPIO_SD_B1_06_USDHC2_RESET_B

/* GPIO_EMC_09 (coord C2), SEMC_A0 */
#define BOARD_INITPINS_SEMC_A0_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A0_SIGNAL                                       ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A0_CHANNEL                                        0U   /*!< SEMC ADDR channel: 00 */
#define BOARD_INITPINS_SEMC_A0_PIN_NAME                              GPIO_EMC_09   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A0_LABEL                                   "SEMC_A0"   /*!< Label */
#define BOARD_INITPINS_SEMC_A0_NAME                                    "SEMC_A0"   /*!< Identifier name */

/* GPIO_EMC_10 (coord G1), SEMC_A1 */
#define BOARD_INITPINS_SEMC_A1_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A1_SIGNAL                                       ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A1_CHANNEL                                        1U   /*!< SEMC ADDR channel: 01 */
#define BOARD_INITPINS_SEMC_A1_PIN_NAME                              GPIO_EMC_10   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A1_LABEL                                   "SEMC_A1"   /*!< Label */
#define BOARD_INITPINS_SEMC_A1_NAME                                    "SEMC_A1"   /*!< Identifier name */

/* GPIO_EMC_11 (coord G3), SEMC_A2 */
#define BOARD_INITPINS_SEMC_A2_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A2_SIGNAL                                       ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A2_CHANNEL                                        2U   /*!< SEMC ADDR channel: 02 */
#define BOARD_INITPINS_SEMC_A2_PIN_NAME                              GPIO_EMC_11   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A2_LABEL                                   "SEMC_A2"   /*!< Label */
#define BOARD_INITPINS_SEMC_A2_NAME                                    "SEMC_A2"   /*!< Identifier name */

/* GPIO_EMC_12 (coord H1), SEMC_A3 */
#define BOARD_INITPINS_SEMC_A3_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A3_SIGNAL                                       ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A3_CHANNEL                                        3U   /*!< SEMC ADDR channel: 03 */
#define BOARD_INITPINS_SEMC_A3_PIN_NAME                              GPIO_EMC_12   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A3_LABEL                                   "SEMC_A3"   /*!< Label */
#define BOARD_INITPINS_SEMC_A3_NAME                                    "SEMC_A3"   /*!< Identifier name */

/* GPIO_EMC_13 (coord A6), SEMC_A4 */
#define BOARD_INITPINS_SEMC_A4_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A4_SIGNAL                                       ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A4_CHANNEL                                        4U   /*!< SEMC ADDR channel: 04 */
#define BOARD_INITPINS_SEMC_A4_PIN_NAME                              GPIO_EMC_13   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A4_LABEL                                   "SEMC_A4"   /*!< Label */
#define BOARD_INITPINS_SEMC_A4_NAME                                    "SEMC_A4"   /*!< Identifier name */

/* GPIO_EMC_14 (coord B6), SEMC_A5 */
#define BOARD_INITPINS_SEMC_A5_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A5_SIGNAL                                       ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A5_CHANNEL                                        5U   /*!< SEMC ADDR channel: 05 */
#define BOARD_INITPINS_SEMC_A5_PIN_NAME                              GPIO_EMC_14   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A5_LABEL                                   "SEMC_A5"   /*!< Label */
#define BOARD_INITPINS_SEMC_A5_NAME                                    "SEMC_A5"   /*!< Identifier name */

/* GPIO_EMC_15 (coord B1), SEMC_A6 */
#define BOARD_INITPINS_SEMC_A6_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A6_SIGNAL                                       ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A6_CHANNEL                                        6U   /*!< SEMC ADDR channel: 06 */
#define BOARD_INITPINS_SEMC_A6_PIN_NAME                              GPIO_EMC_15   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A6_LABEL                                   "SEMC_A6"   /*!< Label */
#define BOARD_INITPINS_SEMC_A6_NAME                                    "SEMC_A6"   /*!< Identifier name */

/* GPIO_EMC_16 (coord A5), SEMC_A7 */
#define BOARD_INITPINS_SEMC_A7_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A7_SIGNAL                                       ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A7_CHANNEL                                        7U   /*!< SEMC ADDR channel: 07 */
#define BOARD_INITPINS_SEMC_A7_PIN_NAME                              GPIO_EMC_16   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A7_LABEL                                   "SEMC_A7"   /*!< Label */
#define BOARD_INITPINS_SEMC_A7_NAME                                    "SEMC_A7"   /*!< Identifier name */

/* GPIO_EMC_17 (coord A4), SEMC_A8 */
#define BOARD_INITPINS_SEMC_A8_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A8_SIGNAL                                       ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A8_CHANNEL                                        8U   /*!< SEMC ADDR channel: 08 */
#define BOARD_INITPINS_SEMC_A8_PIN_NAME                              GPIO_EMC_17   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A8_LABEL                                   "SEMC_A8"   /*!< Label */
#define BOARD_INITPINS_SEMC_A8_NAME                                    "SEMC_A8"   /*!< Identifier name */

/* GPIO_EMC_18 (coord B2), SEMC_A9 */
#define BOARD_INITPINS_SEMC_A9_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A9_SIGNAL                                       ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A9_CHANNEL                                        9U   /*!< SEMC ADDR channel: 09 */
#define BOARD_INITPINS_SEMC_A9_PIN_NAME                              GPIO_EMC_18   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A9_LABEL                                   "SEMC_A9"   /*!< Label */
#define BOARD_INITPINS_SEMC_A9_NAME                                    "SEMC_A9"   /*!< Identifier name */

/* GPIO_EMC_23 (coord G2), SEMC_A10 */
#define BOARD_INITPINS_SEMC_A10_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A10_SIGNAL                                      ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A10_CHANNEL                                      10U   /*!< SEMC ADDR channel: 10 */
#define BOARD_INITPINS_SEMC_A10_PIN_NAME                             GPIO_EMC_23   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A10_LABEL                                 "SEMC_A10"   /*!< Label */
#define BOARD_INITPINS_SEMC_A10_NAME                                  "SEMC_A10"   /*!< Identifier name */

/* GPIO_EMC_19 (coord B4), SEMC_A11 */
#define BOARD_INITPINS_SEMC_A11_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_A11_SIGNAL                                      ADDR   /*!< SEMC signal: ADDR */
#define BOARD_INITPINS_SEMC_A11_CHANNEL                                      11U   /*!< SEMC ADDR channel: 11 */
#define BOARD_INITPINS_SEMC_A11_PIN_NAME                             GPIO_EMC_19   /*!< Pin name */
#define BOARD_INITPINS_SEMC_A11_LABEL                                 "SEMC_A11"   /*!< Label */
#define BOARD_INITPINS_SEMC_A11_NAME                                  "SEMC_A11"   /*!< Identifier name */

/* GPIO_EMC_21 (coord C1), SEMC_BA0 */
#define BOARD_INITPINS_SEMC_BA0_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_BA0_SIGNAL                                        BA   /*!< SEMC signal: BA */
#define BOARD_INITPINS_SEMC_BA0_CHANNEL                                       0U   /*!< SEMC BA channel: 0 */
#define BOARD_INITPINS_SEMC_BA0_PIN_NAME                             GPIO_EMC_21   /*!< Pin name */
#define BOARD_INITPINS_SEMC_BA0_LABEL                                 "SEMC_BA0"   /*!< Label */
#define BOARD_INITPINS_SEMC_BA0_NAME                                  "SEMC_BA0"   /*!< Identifier name */

/* GPIO_EMC_22 (coord F1), SEMC_BA1 */
#define BOARD_INITPINS_SEMC_BA1_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_BA1_SIGNAL                                        BA   /*!< SEMC signal: BA */
#define BOARD_INITPINS_SEMC_BA1_CHANNEL                                       1U   /*!< SEMC BA channel: 1 */
#define BOARD_INITPINS_SEMC_BA1_PIN_NAME                             GPIO_EMC_22   /*!< Pin name */
#define BOARD_INITPINS_SEMC_BA1_LABEL                                 "SEMC_BA1"   /*!< Label */
#define BOARD_INITPINS_SEMC_BA1_NAME                                  "SEMC_BA1"   /*!< Identifier name */

/* GPIO_EMC_24 (coord D3), SEMC_CAS */
#define BOARD_INITPINS_SEMC_CAS_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_CAS_SIGNAL                                  semc_cas   /*!< SEMC signal: semc_cas */
#define BOARD_INITPINS_SEMC_CAS_PIN_NAME                             GPIO_EMC_24   /*!< Pin name */
#define BOARD_INITPINS_SEMC_CAS_LABEL                                 "SEMC_CAS"   /*!< Label */
#define BOARD_INITPINS_SEMC_CAS_NAME                                  "SEMC_CAS"   /*!< Identifier name */

/* GPIO_EMC_27 (coord A2), SEMC_CKE */
#define BOARD_INITPINS_SEMC_CKE_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_CKE_SIGNAL                                  semc_cke   /*!< SEMC signal: semc_cke */
#define BOARD_INITPINS_SEMC_CKE_PIN_NAME                             GPIO_EMC_27   /*!< Pin name */
#define BOARD_INITPINS_SEMC_CKE_LABEL                                 "SEMC_CKE"   /*!< Label */
#define BOARD_INITPINS_SEMC_CKE_NAME                                  "SEMC_CKE"   /*!< Identifier name */

/* GPIO_EMC_26 (coord B3), SEMC_CLK */
#define BOARD_INITPINS_SEMC_CLK_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_CLK_SIGNAL                                  semc_clk   /*!< SEMC signal: semc_clk */
#define BOARD_INITPINS_SEMC_CLK_PIN_NAME                             GPIO_EMC_26   /*!< Pin name */
#define BOARD_INITPINS_SEMC_CLK_LABEL                                 "SEMC_CLK"   /*!< Label */
#define BOARD_INITPINS_SEMC_CLK_NAME                                  "SEMC_CLK"   /*!< Identifier name */

/* GPIO_EMC_29 (coord E1), SEMC_CS0 */
#define BOARD_INITPINS_SEMC_CS0_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_CS0_SIGNAL                                        CS   /*!< SEMC signal: CS */
#define BOARD_INITPINS_SEMC_CS0_CHANNEL                                       0U   /*!< SEMC CS channel: 0 */
#define BOARD_INITPINS_SEMC_CS0_PIN_NAME                             GPIO_EMC_29   /*!< Pin name */
#define BOARD_INITPINS_SEMC_CS0_LABEL                                 "SEMC_CS0"   /*!< Label */
#define BOARD_INITPINS_SEMC_CS0_NAME                                  "SEMC_CS0"   /*!< Identifier name */

/* GPIO_EMC_41 (coord C7), ENET_MDIO */
#define BOARD_INITPINS_ENET_MDIO_PERIPHERAL                                 SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_ENET_MDIO_SIGNAL                                      CSX   /*!< SEMC signal: CSX */
#define BOARD_INITPINS_ENET_MDIO_CHANNEL                                      0U   /*!< SEMC CSX channel: 0 */
#define BOARD_INITPINS_ENET_MDIO_PIN_NAME                            GPIO_EMC_41   /*!< Pin name */
#define BOARD_INITPINS_ENET_MDIO_LABEL                               "ENET_MDIO"   /*!< Label */
#define BOARD_INITPINS_ENET_MDIO_NAME                                "ENET_MDIO"   /*!< Identifier name */

/* GPIO_B0_00 (coord D7), LCDIF_CLK */
#define BOARD_INITPINS_LCDIF_CLK_PERIPHERAL                                 SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_LCDIF_CLK_SIGNAL                                      CSX   /*!< SEMC signal: CSX */
#define BOARD_INITPINS_LCDIF_CLK_CHANNEL                                      1U   /*!< SEMC CSX channel: 1 */
#define BOARD_INITPINS_LCDIF_CLK_PIN_NAME                             GPIO_B0_00   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_CLK_LABEL                               "LCDIF_CLK"   /*!< Label */
#define BOARD_INITPINS_LCDIF_CLK_NAME                                "LCDIF_CLK"   /*!< Identifier name */

/* GPIO_B0_01 (coord E7), LCDIF_ENABLE */
#define BOARD_INITPINS_LCDIF_ENABLE_PERIPHERAL                              SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_LCDIF_ENABLE_SIGNAL                                   CSX   /*!< SEMC signal: CSX */
#define BOARD_INITPINS_LCDIF_ENABLE_CHANNEL                                   2U   /*!< SEMC CSX channel: 2 */
#define BOARD_INITPINS_LCDIF_ENABLE_PIN_NAME                          GPIO_B0_01   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_ENABLE_LABEL                         "LCDIF_ENABLE"   /*!< Label */
#define BOARD_INITPINS_LCDIF_ENABLE_NAME                          "LCDIF_ENABLE"   /*!< Identifier name */

/* GPIO_B0_02 (coord E8), LCDIF_HSYNC */
#define BOARD_INITPINS_LCDIF_HSYNC_PERIPHERAL                               SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_LCDIF_HSYNC_SIGNAL                                    CSX   /*!< SEMC signal: CSX */
#define BOARD_INITPINS_LCDIF_HSYNC_CHANNEL                                    3U   /*!< SEMC CSX channel: 3 */
#define BOARD_INITPINS_LCDIF_HSYNC_PIN_NAME                           GPIO_B0_02   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_HSYNC_LABEL                           "LCDIF_HSYNC"   /*!< Label */
#define BOARD_INITPINS_LCDIF_HSYNC_NAME                            "LCDIF_HSYNC"   /*!< Identifier name */

/* GPIO_EMC_00 (coord E3), SEMC_D0 */
#define BOARD_INITPINS_SEMC_D0_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D0_SIGNAL                                       DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D0_CHANNEL                                        0U   /*!< SEMC DATA channel: 00 */
#define BOARD_INITPINS_SEMC_D0_PIN_NAME                              GPIO_EMC_00   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D0_LABEL                                   "SEMC_D0"   /*!< Label */
#define BOARD_INITPINS_SEMC_D0_NAME                                    "SEMC_D0"   /*!< Identifier name */

/* GPIO_EMC_02 (coord F4), SEMC_D2 */
#define BOARD_INITPINS_SEMC_D2_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D2_SIGNAL                                       DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D2_CHANNEL                                        2U   /*!< SEMC DATA channel: 02 */
#define BOARD_INITPINS_SEMC_D2_PIN_NAME                              GPIO_EMC_02   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D2_LABEL                                   "SEMC_D2"   /*!< Label */
#define BOARD_INITPINS_SEMC_D2_NAME                                    "SEMC_D2"   /*!< Identifier name */

/* GPIO_EMC_03 (coord G4), SEMC_D3 */
#define BOARD_INITPINS_SEMC_D3_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D3_SIGNAL                                       DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D3_CHANNEL                                        3U   /*!< SEMC DATA channel: 03 */
#define BOARD_INITPINS_SEMC_D3_PIN_NAME                              GPIO_EMC_03   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D3_LABEL                                   "SEMC_D3"   /*!< Label */
#define BOARD_INITPINS_SEMC_D3_NAME                                    "SEMC_D3"   /*!< Identifier name */

/* GPIO_EMC_04 (coord F2), SEMC_D4 */
#define BOARD_INITPINS_SEMC_D4_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D4_SIGNAL                                       DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D4_CHANNEL                                        4U   /*!< SEMC DATA channel: 04 */
#define BOARD_INITPINS_SEMC_D4_PIN_NAME                              GPIO_EMC_04   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D4_LABEL                                   "SEMC_D4"   /*!< Label */
#define BOARD_INITPINS_SEMC_D4_NAME                                    "SEMC_D4"   /*!< Identifier name */

/* GPIO_EMC_05 (coord G5), SEMC_D5 */
#define BOARD_INITPINS_SEMC_D5_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D5_SIGNAL                                       DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D5_CHANNEL                                        5U   /*!< SEMC DATA channel: 05 */
#define BOARD_INITPINS_SEMC_D5_PIN_NAME                              GPIO_EMC_05   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D5_LABEL                                   "SEMC_D5"   /*!< Label */
#define BOARD_INITPINS_SEMC_D5_NAME                                    "SEMC_D5"   /*!< Identifier name */

/* GPIO_EMC_06 (coord H5), SEMC_D6 */
#define BOARD_INITPINS_SEMC_D6_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D6_SIGNAL                                       DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D6_CHANNEL                                        6U   /*!< SEMC DATA channel: 06 */
#define BOARD_INITPINS_SEMC_D6_PIN_NAME                              GPIO_EMC_06   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D6_LABEL                                   "SEMC_D6"   /*!< Label */
#define BOARD_INITPINS_SEMC_D6_NAME                                    "SEMC_D6"   /*!< Identifier name */

/* GPIO_EMC_07 (coord H4), SEMC_D7 */
#define BOARD_INITPINS_SEMC_D7_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D7_SIGNAL                                       DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D7_CHANNEL                                        7U   /*!< SEMC DATA channel: 07 */
#define BOARD_INITPINS_SEMC_D7_PIN_NAME                              GPIO_EMC_07   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D7_LABEL                                   "SEMC_D7"   /*!< Label */
#define BOARD_INITPINS_SEMC_D7_NAME                                    "SEMC_D7"   /*!< Identifier name */

/* GPIO_EMC_30 (coord C6), SEMC_D8 */
#define BOARD_INITPINS_SEMC_D8_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D8_SIGNAL                                       DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D8_CHANNEL                                        8U   /*!< SEMC DATA channel: 08 */
#define BOARD_INITPINS_SEMC_D8_PIN_NAME                              GPIO_EMC_30   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D8_LABEL                                   "SEMC_D8"   /*!< Label */
#define BOARD_INITPINS_SEMC_D8_NAME                                    "SEMC_D8"   /*!< Identifier name */

/* GPIO_EMC_31 (coord C5), SEMC_D9 */
#define BOARD_INITPINS_SEMC_D9_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D9_SIGNAL                                       DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D9_CHANNEL                                        9U   /*!< SEMC DATA channel: 09 */
#define BOARD_INITPINS_SEMC_D9_PIN_NAME                              GPIO_EMC_31   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D9_LABEL                                   "SEMC_D9"   /*!< Label */
#define BOARD_INITPINS_SEMC_D9_NAME                                    "SEMC_D9"   /*!< Identifier name */

/* GPIO_EMC_32 (coord D5), SEMC_D10 */
#define BOARD_INITPINS_SEMC_D10_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D10_SIGNAL                                      DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D10_CHANNEL                                      10U   /*!< SEMC DATA channel: 10 */
#define BOARD_INITPINS_SEMC_D10_PIN_NAME                             GPIO_EMC_32   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D10_LABEL                                 "SEMC_D10"   /*!< Label */
#define BOARD_INITPINS_SEMC_D10_NAME                                  "SEMC_D10"   /*!< Identifier name */

/* GPIO_EMC_33 (coord C4), SEMC_D11 */
#define BOARD_INITPINS_SEMC_D11_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D11_SIGNAL                                      DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D11_CHANNEL                                      11U   /*!< SEMC DATA channel: 11 */
#define BOARD_INITPINS_SEMC_D11_PIN_NAME                             GPIO_EMC_33   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D11_LABEL                                 "SEMC_D11"   /*!< Label */
#define BOARD_INITPINS_SEMC_D11_NAME                                  "SEMC_D11"   /*!< Identifier name */

/* GPIO_EMC_34 (coord D4), SEMC_D12 */
#define BOARD_INITPINS_SEMC_D12_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D12_SIGNAL                                      DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D12_CHANNEL                                      12U   /*!< SEMC DATA channel: 12 */
#define BOARD_INITPINS_SEMC_D12_PIN_NAME                             GPIO_EMC_34   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D12_LABEL                                 "SEMC_D12"   /*!< Label */
#define BOARD_INITPINS_SEMC_D12_NAME                                  "SEMC_D12"   /*!< Identifier name */

/* GPIO_EMC_35 (coord E5), SEMC_D13 */
#define BOARD_INITPINS_SEMC_D13_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D13_SIGNAL                                      DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D13_CHANNEL                                      13U   /*!< SEMC DATA channel: 13 */
#define BOARD_INITPINS_SEMC_D13_PIN_NAME                             GPIO_EMC_35   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D13_LABEL                                 "SEMC_D13"   /*!< Label */
#define BOARD_INITPINS_SEMC_D13_NAME                                  "SEMC_D13"   /*!< Identifier name */

/* GPIO_EMC_36 (coord C3), SEMC_D14 */
#define BOARD_INITPINS_SEMC_D14_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D14_SIGNAL                                      DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D14_CHANNEL                                      14U   /*!< SEMC DATA channel: 14 */
#define BOARD_INITPINS_SEMC_D14_PIN_NAME                             GPIO_EMC_36   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D14_LABEL                                 "SEMC_D14"   /*!< Label */
#define BOARD_INITPINS_SEMC_D14_NAME                                  "SEMC_D14"   /*!< Identifier name */

/* GPIO_EMC_37 (coord E4), SEMC_D15 */
#define BOARD_INITPINS_SEMC_D15_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D15_SIGNAL                                      DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D15_CHANNEL                                      15U   /*!< SEMC DATA channel: 15 */
#define BOARD_INITPINS_SEMC_D15_PIN_NAME                             GPIO_EMC_37   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D15_LABEL                                 "SEMC_D15"   /*!< Label */
#define BOARD_INITPINS_SEMC_D15_NAME                                  "SEMC_D15"   /*!< Identifier name */

/* GPIO_EMC_08 (coord H3), SEMC_DM0 */
#define BOARD_INITPINS_SEMC_DM0_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_DM0_SIGNAL                                        DM   /*!< SEMC signal: DM */
#define BOARD_INITPINS_SEMC_DM0_CHANNEL                                       0U   /*!< SEMC DM channel: 0 */
#define BOARD_INITPINS_SEMC_DM0_PIN_NAME                             GPIO_EMC_08   /*!< Pin name */
#define BOARD_INITPINS_SEMC_DM0_LABEL                                 "SEMC_DM0"   /*!< Label */
#define BOARD_INITPINS_SEMC_DM0_NAME                                  "SEMC_DM0"   /*!< Identifier name */

/* GPIO_EMC_38 (coord D6), SEMC_DM1 */
#define BOARD_INITPINS_SEMC_DM1_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_DM1_SIGNAL                                        DM   /*!< SEMC signal: DM */
#define BOARD_INITPINS_SEMC_DM1_CHANNEL                                       1U   /*!< SEMC DM channel: 1 */
#define BOARD_INITPINS_SEMC_DM1_PIN_NAME                             GPIO_EMC_38   /*!< Pin name */
#define BOARD_INITPINS_SEMC_DM1_LABEL                                 "SEMC_DM1"   /*!< Label */
#define BOARD_INITPINS_SEMC_DM1_NAME                                  "SEMC_DM1"   /*!< Identifier name */

/* GPIO_EMC_39 (coord B7), SEMC_DQS */
#define BOARD_INITPINS_SEMC_DQS_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_DQS_SIGNAL                                  semc_dqs   /*!< SEMC signal: semc_dqs */
#define BOARD_INITPINS_SEMC_DQS_PIN_NAME                             GPIO_EMC_39   /*!< Pin name */
#define BOARD_INITPINS_SEMC_DQS_LABEL                                 "SEMC_DQS"   /*!< Label */
#define BOARD_INITPINS_SEMC_DQS_NAME                                  "SEMC_DQS"   /*!< Identifier name */

/* GPIO_EMC_25 (coord D2), SEMC_RAS */
#define BOARD_INITPINS_SEMC_RAS_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_RAS_SIGNAL                                  semc_ras   /*!< SEMC signal: semc_ras */
#define BOARD_INITPINS_SEMC_RAS_PIN_NAME                             GPIO_EMC_25   /*!< Pin name */
#define BOARD_INITPINS_SEMC_RAS_LABEL                                 "SEMC_RAS"   /*!< Label */
#define BOARD_INITPINS_SEMC_RAS_NAME                                  "SEMC_RAS"   /*!< Identifier name */

/* GPIO_EMC_40 (coord A7), ENET_MDC */
#define BOARD_INITPINS_ENET_MDC_PERIPHERAL                                  SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_ENET_MDC_SIGNAL                                  semc_rdy   /*!< SEMC signal: semc_rdy */
#define BOARD_INITPINS_ENET_MDC_PIN_NAME                             GPIO_EMC_40   /*!< Pin name */
#define BOARD_INITPINS_ENET_MDC_LABEL                                 "ENET_MDC"   /*!< Label */
#define BOARD_INITPINS_ENET_MDC_NAME                                  "ENET_MDC"   /*!< Identifier name */

/* GPIO_EMC_28 (coord D1), SEMC_WE */
#define BOARD_INITPINS_SEMC_WE_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_WE_SIGNAL                                    semc_we   /*!< SEMC signal: semc_we */
#define BOARD_INITPINS_SEMC_WE_PIN_NAME                              GPIO_EMC_28   /*!< Pin name */
#define BOARD_INITPINS_SEMC_WE_LABEL                                   "SEMC_WE"   /*!< Label */
#define BOARD_INITPINS_SEMC_WE_NAME                                    "SEMC_WE"   /*!< Identifier name */

/* GPIO_AD_B0_05 (coord G14), CAN_STBY/BOOT_MODE[1]/Flash_RST/U12[8] */
#define BOARD_INITPINS_CAN_STBY_PERIPHERAL                                  SAI2   /*!< Device name: SAI2 */
#define BOARD_INITPINS_CAN_STBY_SIGNAL                               sai_tx_bclk   /*!< SAI2 signal: sai_tx_bclk */
#define BOARD_INITPINS_CAN_STBY_PIN_NAME                           GPIO_AD_B0_05   /*!< Pin name */
#define BOARD_INITPINS_CAN_STBY_LABEL   "CAN_STBY/BOOT_MODE[1]/Flash_RST/U12[8]"   /*!< Label */
#define BOARD_INITPINS_CAN_STBY_NAME                                  "CAN_STBY"   /*!< Identifier name */

/* GPIO_AD_B0_14 (coord H14), CAN2_TX/U12[1] */
#define BOARD_INITPINS_CAN2_TX_PERIPHERAL                                LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITPINS_CAN2_TX_SIGNAL                                      CTS_B   /*!< LPUART1 signal: CTS_B */
#define BOARD_INITPINS_CAN2_TX_PIN_NAME                            GPIO_AD_B0_14   /*!< Pin name */
#define BOARD_INITPINS_CAN2_TX_LABEL                            "CAN2_TX/U12[1]"   /*!< Label */
#define BOARD_INITPINS_CAN2_TX_NAME                                    "CAN2_TX"   /*!< Identifier name */

/* GPIO_AD_B0_15 (coord L10), CAN2_RX/U12[4] */
#define BOARD_INITPINS_CAN2_RX_PERIPHERAL                                LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITPINS_CAN2_RX_SIGNAL                                      RTS_B   /*!< LPUART1 signal: RTS_B */
#define BOARD_INITPINS_CAN2_RX_PIN_NAME                            GPIO_AD_B0_15   /*!< Pin name */
#define BOARD_INITPINS_CAN2_RX_LABEL                            "CAN2_RX/U12[4]"   /*!< Label */
#define BOARD_INITPINS_CAN2_RX_NAME                                    "CAN2_RX"   /*!< Identifier name */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< LPUART1 signal: RX */
#define BOARD_INITPINS_UART1_RXD_PIN_NAME                          GPIO_AD_B0_13   /*!< Pin name */
#define BOARD_INITPINS_UART1_RXD_LABEL                               "UART1_RXD"   /*!< Label */
#define BOARD_INITPINS_UART1_RXD_NAME                                "UART1_RXD"   /*!< Identifier name */

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Device name: LPUART1 */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< LPUART1 signal: TX */
#define BOARD_INITPINS_UART1_TXD_PIN_NAME                          GPIO_AD_B0_12   /*!< Pin name */
#define BOARD_INITPINS_UART1_TXD_LABEL                               "UART1_TXD"   /*!< Label */
#define BOARD_INITPINS_UART1_TXD_NAME                                "UART1_TXD"   /*!< Identifier name */

/* GPIO_AD_B1_03 (coord M12), SPDIF_IN/J22[8] */
#define BOARD_INITPINS_SPDIF_IN_PERIPHERAL                               LPUART2   /*!< Device name: LPUART2 */
#define BOARD_INITPINS_SPDIF_IN_SIGNAL                                        RX   /*!< LPUART2 signal: RX */
#define BOARD_INITPINS_SPDIF_IN_PIN_NAME                           GPIO_AD_B1_03   /*!< Pin name */
#define BOARD_INITPINS_SPDIF_IN_LABEL                          "SPDIF_IN/J22[8]"   /*!< Label */
#define BOARD_INITPINS_SPDIF_IN_NAME                                  "SPDIF_IN"   /*!< Identifier name */

/* GPIO_AD_B1_02 (coord L11), SPDIF_OUT/J22[7] */
#define BOARD_INITPINS_SPDIF_OUT_PERIPHERAL                              LPUART2   /*!< Device name: LPUART2 */
#define BOARD_INITPINS_SPDIF_OUT_SIGNAL                                       TX   /*!< LPUART2 signal: TX */
#define BOARD_INITPINS_SPDIF_OUT_PIN_NAME                          GPIO_AD_B1_02   /*!< Pin name */
#define BOARD_INITPINS_SPDIF_OUT_LABEL                        "SPDIF_OUT/J22[7]"   /*!< Label */
#define BOARD_INITPINS_SPDIF_OUT_NAME                                "SPDIF_OUT"   /*!< Identifier name */

/* GPIO_AD_B1_07 (coord K10), CSI_HSYNC/J35[16]/J22[1]/UART_RX */
#define BOARD_INITPINS_CSI_HSYNC_PERIPHERAL                              LPUART3   /*!< Device name: LPUART3 */
#define BOARD_INITPINS_CSI_HSYNC_SIGNAL                                       RX   /*!< LPUART3 signal: RX */
#define BOARD_INITPINS_CSI_HSYNC_PIN_NAME                          GPIO_AD_B1_07   /*!< Pin name */
#define BOARD_INITPINS_CSI_HSYNC_LABEL        "CSI_HSYNC/J35[16]/J22[1]/UART_RX"   /*!< Label */
#define BOARD_INITPINS_CSI_HSYNC_NAME                                "CSI_HSYNC"   /*!< Identifier name */

/* GPIO_AD_B1_06 (coord J12), CSI_VSYNC/J35[18]/J22[2]/UART_TX */
#define BOARD_INITPINS_CSI_VSYNC_PERIPHERAL                              LPUART3   /*!< Device name: LPUART3 */
#define BOARD_INITPINS_CSI_VSYNC_SIGNAL                                       TX   /*!< LPUART3 signal: TX */
#define BOARD_INITPINS_CSI_VSYNC_PIN_NAME                          GPIO_AD_B1_06   /*!< Pin name */
#define BOARD_INITPINS_CSI_VSYNC_LABEL        "CSI_VSYNC/J35[18]/J22[2]/UART_TX"   /*!< Label */
#define BOARD_INITPINS_CSI_VSYNC_NAME                                "CSI_VSYNC"   /*!< Identifier name */

/* GPIO_SD_B1_04 (coord P2), FlexSPI_CLK_B */
#define BOARD_INITPINS_FlexSPI_CLK_B_PERIPHERAL                           USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_CLK_B_SIGNAL                            usdhc_clk   /*!< USDHC2 signal: usdhc_clk */
#define BOARD_INITPINS_FlexSPI_CLK_B_PIN_NAME                      GPIO_SD_B1_04   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_CLK_B_LABEL                       "FlexSPI_CLK_B"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_CLK_B_NAME                        "FlexSPI_CLK_B"   /*!< Identifier name */

/* GPIO_SD_B1_05 (coord N3), FlexSPI_DQS */
#define BOARD_INITPINS_FlexSPI_DQS_PERIPHERAL                             USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_DQS_SIGNAL                              usdhc_cmd   /*!< USDHC2 signal: usdhc_cmd */
#define BOARD_INITPINS_FlexSPI_DQS_PIN_NAME                        GPIO_SD_B1_05   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_DQS_LABEL                           "FlexSPI_DQS"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_DQS_NAME                            "FlexSPI_DQS"   /*!< Identifier name */

/* GPIO_SD_B1_03 (coord M4), FlexSPI_D0_B */
#define BOARD_INITPINS_FlexSPI_D0_B_PERIPHERAL                            USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_D0_B_SIGNAL                            usdhc_data   /*!< USDHC2 signal: usdhc_data */
#define BOARD_INITPINS_FlexSPI_D0_B_CHANNEL                                   0U   /*!< USDHC2 usdhc_data channel: 0 */
#define BOARD_INITPINS_FlexSPI_D0_B_PIN_NAME                       GPIO_SD_B1_03   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_D0_B_LABEL                         "FlexSPI_D0_B"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_D0_B_NAME                          "FlexSPI_D0_B"   /*!< Identifier name */

/* GPIO_SD_B1_02 (coord M3), FlexSPI_D1_B */
#define BOARD_INITPINS_FlexSPI_D1_B_PERIPHERAL                            USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_D1_B_SIGNAL                            usdhc_data   /*!< USDHC2 signal: usdhc_data */
#define BOARD_INITPINS_FlexSPI_D1_B_CHANNEL                                   1U   /*!< USDHC2 usdhc_data channel: 1 */
#define BOARD_INITPINS_FlexSPI_D1_B_PIN_NAME                       GPIO_SD_B1_02   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_D1_B_LABEL                         "FlexSPI_D1_B"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_D1_B_NAME                          "FlexSPI_D1_B"   /*!< Identifier name */

/* GPIO_SD_B1_01 (coord M5), FlexSPI_D2_B */
#define BOARD_INITPINS_FlexSPI_D2_B_PERIPHERAL                            USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_D2_B_SIGNAL                            usdhc_data   /*!< USDHC2 signal: usdhc_data */
#define BOARD_INITPINS_FlexSPI_D2_B_CHANNEL                                   2U   /*!< USDHC2 usdhc_data channel: 2 */
#define BOARD_INITPINS_FlexSPI_D2_B_PIN_NAME                       GPIO_SD_B1_01   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_D2_B_LABEL                         "FlexSPI_D2_B"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_D2_B_NAME                          "FlexSPI_D2_B"   /*!< Identifier name */

/* GPIO_SD_B1_00 (coord L5), FlexSPI_D3_B */
#define BOARD_INITPINS_FlexSPI_D3_B_PERIPHERAL                            USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_D3_B_SIGNAL                            usdhc_data   /*!< USDHC2 signal: usdhc_data */
#define BOARD_INITPINS_FlexSPI_D3_B_CHANNEL                                   3U   /*!< USDHC2 usdhc_data channel: 3 */
#define BOARD_INITPINS_FlexSPI_D3_B_PIN_NAME                       GPIO_SD_B1_00   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_D3_B_LABEL                         "FlexSPI_D3_B"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_D3_B_NAME                          "FlexSPI_D3_B"   /*!< Identifier name */

/* GPIO_SD_B1_08 (coord P3), FlexSPI_D0_A */
#define BOARD_INITPINS_FlexSPI_D0_A_PERIPHERAL                            USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_D0_A_SIGNAL                            usdhc_data   /*!< USDHC2 signal: usdhc_data */
#define BOARD_INITPINS_FlexSPI_D0_A_CHANNEL                                   4U   /*!< USDHC2 usdhc_data channel: 4 */
#define BOARD_INITPINS_FlexSPI_D0_A_PIN_NAME                       GPIO_SD_B1_08   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_D0_A_LABEL                         "FlexSPI_D0_A"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_D0_A_NAME                          "FlexSPI_D0_A"   /*!< Identifier name */

/* GPIO_SD_B1_09 (coord N4), FlexSPI_D1_A */
#define BOARD_INITPINS_FlexSPI_D1_A_PERIPHERAL                            USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_D1_A_SIGNAL                            usdhc_data   /*!< USDHC2 signal: usdhc_data */
#define BOARD_INITPINS_FlexSPI_D1_A_CHANNEL                                   5U   /*!< USDHC2 usdhc_data channel: 5 */
#define BOARD_INITPINS_FlexSPI_D1_A_PIN_NAME                       GPIO_SD_B1_09   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_D1_A_LABEL                         "FlexSPI_D1_A"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_D1_A_NAME                          "FlexSPI_D1_A"   /*!< Identifier name */

/* GPIO_SD_B1_10 (coord P4), FlexSPI_D2_A */
#define BOARD_INITPINS_FlexSPI_D2_A_PERIPHERAL                            USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_D2_A_SIGNAL                            usdhc_data   /*!< USDHC2 signal: usdhc_data */
#define BOARD_INITPINS_FlexSPI_D2_A_CHANNEL                                   6U   /*!< USDHC2 usdhc_data channel: 6 */
#define BOARD_INITPINS_FlexSPI_D2_A_PIN_NAME                       GPIO_SD_B1_10   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_D2_A_LABEL                         "FlexSPI_D2_A"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_D2_A_NAME                          "FlexSPI_D2_A"   /*!< Identifier name */

/* GPIO_SD_B1_11 (coord P5), FlexSPI_D3_A */
#define BOARD_INITPINS_FlexSPI_D3_A_PERIPHERAL                            USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_D3_A_SIGNAL                            usdhc_data   /*!< USDHC2 signal: usdhc_data */
#define BOARD_INITPINS_FlexSPI_D3_A_CHANNEL                                   7U   /*!< USDHC2 usdhc_data channel: 7 */
#define BOARD_INITPINS_FlexSPI_D3_A_PIN_NAME                       GPIO_SD_B1_11   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_D3_A_LABEL                         "FlexSPI_D3_A"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_D3_A_NAME                          "FlexSPI_D3_A"   /*!< Identifier name */

/* GPIO_SD_B1_06 (coord L3), FlexSPI_SS0 */
#define BOARD_INITPINS_FlexSPI_SS0_PERIPHERAL                             USDHC2   /*!< Device name: USDHC2 */
#define BOARD_INITPINS_FlexSPI_SS0_SIGNAL                          usdhc_reset_b   /*!< USDHC2 signal: usdhc_reset_b */
#define BOARD_INITPINS_FlexSPI_SS0_PIN_NAME                        GPIO_SD_B1_06   /*!< Pin name */
#define BOARD_INITPINS_FlexSPI_SS0_LABEL                           "FlexSPI_SS0"   /*!< Label */
#define BOARD_INITPINS_FlexSPI_SS0_NAME                            "FlexSPI_SS0"   /*!< Identifier name */

/* GPIO_SD_B0_00 (coord J4), SD1_CMD/J24[6] */
#define BOARD_INITPINS_SD1_CMD_PERIPHERAL                                 LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SD1_CMD_SIGNAL                                        SCK   /*!< LPSPI1 signal: SCK */
#define BOARD_INITPINS_SD1_CMD_PIN_NAME                            GPIO_SD_B0_00   /*!< Pin name */
#define BOARD_INITPINS_SD1_CMD_LABEL                            "SD1_CMD/J24[6]"   /*!< Label */
#define BOARD_INITPINS_SD1_CMD_NAME                                    "SD1_CMD"   /*!< Identifier name */

/* GPIO_SD_B0_03 (coord K1), SD1_D1/J24[5]/SPI_MISO */
#define BOARD_INITPINS_SD1_D1_PERIPHERAL                                  LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SD1_D1_SIGNAL                                         SDI   /*!< LPSPI1 signal: SDI */
#define BOARD_INITPINS_SD1_D1_PIN_NAME                             GPIO_SD_B0_03   /*!< Pin name */
#define BOARD_INITPINS_SD1_D1_LABEL                     "SD1_D1/J24[5]/SPI_MISO"   /*!< Label */
#define BOARD_INITPINS_SD1_D1_NAME                                      "SD1_D1"   /*!< Identifier name */

/* GPIO_SD_B0_02 (coord J1), SD1_D0/J24[4]/SPI_MOSI/PWM */
#define BOARD_INITPINS_SD1_D0_PERIPHERAL                                  LPSPI1   /*!< Device name: LPSPI1 */
#define BOARD_INITPINS_SD1_D0_SIGNAL                                         SDO   /*!< LPSPI1 signal: SDO */
#define BOARD_INITPINS_SD1_D0_PIN_NAME                             GPIO_SD_B0_02   /*!< Pin name */
#define BOARD_INITPINS_SD1_D0_LABEL                 "SD1_D0/J24[4]/SPI_MOSI/PWM"   /*!< Label */
#define BOARD_INITPINS_SD1_D0_NAME                                      "SD1_D0"   /*!< Identifier name */

/* GPIO_B0_04 (coord C8), LCDIF_D0/BT_CFG[0] */
#define BOARD_INITPINS_LCDIF_D0_PERIPHERAL                                LPI2C2   /*!< Device name: LPI2C2 */
#define BOARD_INITPINS_LCDIF_D0_SIGNAL                                       SCL   /*!< LPI2C2 signal: SCL */
#define BOARD_INITPINS_LCDIF_D0_PIN_NAME                              GPIO_B0_04   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_D0_LABEL                       "LCDIF_D0/BT_CFG[0]"   /*!< Label */
#define BOARD_INITPINS_LCDIF_D0_NAME                                  "LCDIF_D0"   /*!< Identifier name */

/* GPIO_B0_05 (coord B8), LCDIF_D1/BT_CFG[1] */
#define BOARD_INITPINS_LCDIF_D1_PERIPHERAL                                LPI2C2   /*!< Device name: LPI2C2 */
#define BOARD_INITPINS_LCDIF_D1_SIGNAL                                       SDA   /*!< LPI2C2 signal: SDA */
#define BOARD_INITPINS_LCDIF_D1_PIN_NAME                              GPIO_B0_05   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_D1_LABEL                       "LCDIF_D1/BT_CFG[1]"   /*!< Label */
#define BOARD_INITPINS_LCDIF_D1_NAME                                  "LCDIF_D1"   /*!< Identifier name */

/* USB_OTG1_DP (coord L8), OTG1_DP */
#define BOARD_INITPINS_OTG1_DP_PERIPHERAL                                 SUPPLY   /*!< Device name: SUPPLY */
#define BOARD_INITPINS_OTG1_DP_SIGNAL                                usb_otg1_dp   /*!< SUPPLY signal: usb_otg1_dp */
#define BOARD_INITPINS_OTG1_DP_PIN_NAME                              USB_OTG1_DP   /*!< Pin name */
#define BOARD_INITPINS_OTG1_DP_LABEL                                   "OTG1_DP"   /*!< Label */
#define BOARD_INITPINS_OTG1_DP_NAME                                    "OTG1_DP"   /*!< Identifier name */

/* USB_OTG1_DN (coord M8), OTG1_DN */
#define BOARD_INITPINS_OTG1_DN_PERIPHERAL                                 SUPPLY   /*!< Device name: SUPPLY */
#define BOARD_INITPINS_OTG1_DN_SIGNAL                                usb_otg1_dn   /*!< SUPPLY signal: usb_otg1_dn */
#define BOARD_INITPINS_OTG1_DN_PIN_NAME                              USB_OTG1_DN   /*!< Pin name */
#define BOARD_INITPINS_OTG1_DN_LABEL                                   "OTG1_DN"   /*!< Label */
#define BOARD_INITPINS_OTG1_DN_NAME                                    "OTG1_DN"   /*!< Identifier name */

/* GPIO_AD_B1_04 (coord L12), CSI_PIXCLK/J35[8]/J23[3] */
#define BOARD_INITPINS_CSI_PIXCLK_PERIPHERAL                                ADC1   /*!< Device name: ADC1 */
#define BOARD_INITPINS_CSI_PIXCLK_SIGNAL                                      IN   /*!< ADC1 signal: IN */
#define BOARD_INITPINS_CSI_PIXCLK_CHANNEL                                     9U   /*!< ADC1 IN channel: 9 */
#define BOARD_INITPINS_CSI_PIXCLK_PIN_NAME                         GPIO_AD_B1_04   /*!< Pin name */
#define BOARD_INITPINS_CSI_PIXCLK_LABEL               "CSI_PIXCLK/J35[8]/J23[3]"   /*!< Label */
#define BOARD_INITPINS_CSI_PIXCLK_NAME                              "CSI_PIXCLK"   /*!< Identifier name */

/* GPIO_AD_B1_05 (coord K12), CSI_MCLK/J35[12]/J23[4] */
#define BOARD_INITPINS_CSI_MCLK_PERIPHERAL                                  ADC1   /*!< Device name: ADC1 */
#define BOARD_INITPINS_CSI_MCLK_SIGNAL                                        IN   /*!< ADC1 signal: IN */
#define BOARD_INITPINS_CSI_MCLK_CHANNEL                                      10U   /*!< ADC1 IN channel: 10 */
#define BOARD_INITPINS_CSI_MCLK_PIN_NAME                           GPIO_AD_B1_05   /*!< Pin name */
#define BOARD_INITPINS_CSI_MCLK_LABEL                  "CSI_MCLK/J35[12]/J23[4]"   /*!< Label */
#define BOARD_INITPINS_CSI_MCLK_NAME                                  "CSI_MCLK"   /*!< Identifier name */

/* GPIO_AD_B1_08 (coord H13), AUD_INT/CSI_D9//J35[13]/J22[4] */
#define BOARD_INITPINS_CSI_D9_PERIPHERAL                                    ADC1   /*!< Device name: ADC1 */
#define BOARD_INITPINS_CSI_D9_SIGNAL                                          IN   /*!< ADC1 signal: IN */
#define BOARD_INITPINS_CSI_D9_CHANNEL                                        13U   /*!< ADC1 IN channel: 13 */
#define BOARD_INITPINS_CSI_D9_PIN_NAME                             GPIO_AD_B1_08   /*!< Pin name */
#define BOARD_INITPINS_CSI_D9_LABEL             "AUD_INT/CSI_D9//J35[13]/J22[4]"   /*!< Label */
#define BOARD_INITPINS_CSI_D9_NAME                                      "CSI_D9"   /*!< Identifier name */

/* GPIO_B0_03 (coord D8), LCDIF_VSYNC */
#define BOARD_INITPINS_LCDIF_VSYNC_GPIO                                    GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_VSYNC_PORT                                    GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_VSYNC_GPIO_PIN                                   3U   /*!< GPIO2 pin index: 3 */
#define BOARD_INITPINS_LCDIF_VSYNC_PIN_NAME                           GPIO_B0_03   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_VSYNC_LABEL                           "LCDIF_VSYNC"   /*!< Label */
#define BOARD_INITPINS_LCDIF_VSYNC_NAME                            "LCDIF_VSYNC"   /*!< Identifier name */

/* GPIO_B1_00 (coord A11), LCDIF_D12 */
#define BOARD_INITPINS_LCDIF_D12_GPIO                                      GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D12_PORT                                      GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D12_GPIO_PIN                                    16U   /*!< GPIO2 pin index: 16 */
#define BOARD_INITPINS_LCDIF_D12_PIN_NAME                             GPIO_B1_00   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_D12_LABEL                               "LCDIF_D12"   /*!< Label */
#define BOARD_INITPINS_LCDIF_D12_NAME                                "LCDIF_D12"   /*!< Identifier name */

/* GPIO_B1_01 (coord B11), LCDIF_D13 */
#define BOARD_INITPINS_LCDIF_D13_GPIO                                      GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D13_PORT                                      GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D13_GPIO_PIN                                    17U   /*!< GPIO2 pin index: 17 */
#define BOARD_INITPINS_LCDIF_D13_PIN_NAME                             GPIO_B1_01   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_D13_LABEL                               "LCDIF_D13"   /*!< Label */
#define BOARD_INITPINS_LCDIF_D13_NAME                                "LCDIF_D13"   /*!< Identifier name */

/* GPIO_B1_03 (coord D11), LCDIF_D15 */
#define BOARD_INITPINS_LCDIF_D15_GPIO                                      GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D15_PORT                                      GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_LCDIF_D15_GPIO_PIN                                    19U   /*!< GPIO2 pin index: 19 */
#define BOARD_INITPINS_LCDIF_D15_PIN_NAME                             GPIO_B1_03   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_D15_LABEL                               "LCDIF_D15"   /*!< Label */
#define BOARD_INITPINS_LCDIF_D15_NAME                                "LCDIF_D15"   /*!< Identifier name */

/* GPIO_B1_04 (coord E12), ENET_RXD0 */
#define BOARD_INITPINS_ENET_RXD0_GPIO                                      GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_ENET_RXD0_PORT                                      GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_ENET_RXD0_GPIO_PIN                                    20U   /*!< GPIO2 pin index: 20 */
#define BOARD_INITPINS_ENET_RXD0_PIN_NAME                             GPIO_B1_04   /*!< Pin name */
#define BOARD_INITPINS_ENET_RXD0_LABEL                               "ENET_RXD0"   /*!< Label */
#define BOARD_INITPINS_ENET_RXD0_NAME                                "ENET_RXD0"   /*!< Identifier name */

/* GPIO_B1_05 (coord D12), ENET_RXD1 */
#define BOARD_INITPINS_ENET_RXD1_GPIO                                      GPIO2   /*!< GPIO device name: GPIO2 */
#define BOARD_INITPINS_ENET_RXD1_PORT                                      GPIO2   /*!< PORT device name: GPIO2 */
#define BOARD_INITPINS_ENET_RXD1_GPIO_PIN                                    21U   /*!< GPIO2 pin index: 21 */
#define BOARD_INITPINS_ENET_RXD1_PIN_NAME                             GPIO_B1_05   /*!< Pin name */
#define BOARD_INITPINS_ENET_RXD1_LABEL                               "ENET_RXD1"   /*!< Label */
#define BOARD_INITPINS_ENET_RXD1_NAME                                "ENET_RXD1"   /*!< Identifier name */

/* NVCC_SD0 (coord J6), NVCC_SD */
#define BOARD_INITPINS_NVCC_SD_PERIPHERAL                                 SUPPLY   /*!< Device name: SUPPLY */
#define BOARD_INITPINS_NVCC_SD_SIGNAL                                   nvcc_sd0   /*!< SUPPLY signal: nvcc_sd0 */
#define BOARD_INITPINS_NVCC_SD_PIN_NAME                                 NVCC_SD0   /*!< Pin name */
#define BOARD_INITPINS_NVCC_SD_LABEL                                   "NVCC_SD"   /*!< Label */
#define BOARD_INITPINS_NVCC_SD_NAME                                    "NVCC_SD"   /*!< Identifier name */

/* NVCC_SD1 (coord K5), FLASH_VCC */
#define BOARD_INITPINS_FLASH_VCC_PERIPHERAL                               SUPPLY   /*!< Device name: SUPPLY */
#define BOARD_INITPINS_FLASH_VCC_SIGNAL                                 nvcc_sd1   /*!< SUPPLY signal: nvcc_sd1 */
#define BOARD_INITPINS_FLASH_VCC_PIN_NAME                               NVCC_SD1   /*!< Pin name */
#define BOARD_INITPINS_FLASH_VCC_LABEL                               "FLASH_VCC"   /*!< Label */
#define BOARD_INITPINS_FLASH_VCC_NAME                                "FLASH_VCC"   /*!< Identifier name */

/* USB_OTG2_DN (coord N7), OTG2_DN */
#define BOARD_INITPINS_OTG2_DN_PERIPHERAL                                 SUPPLY   /*!< Device name: SUPPLY */
#define BOARD_INITPINS_OTG2_DN_SIGNAL                                usb_otg2_dn   /*!< SUPPLY signal: usb_otg2_dn */
#define BOARD_INITPINS_OTG2_DN_PIN_NAME                              USB_OTG2_DN   /*!< Pin name */
#define BOARD_INITPINS_OTG2_DN_LABEL                                   "OTG2_DN"   /*!< Label */
#define BOARD_INITPINS_OTG2_DN_NAME                                    "OTG2_DN"   /*!< Identifier name */

/* USB_OTG2_DP (coord P7), OTG2_DP */
#define BOARD_INITPINS_OTG2_DP_PERIPHERAL                                 SUPPLY   /*!< Device name: SUPPLY */
#define BOARD_INITPINS_OTG2_DP_SIGNAL                                usb_otg2_dp   /*!< SUPPLY signal: usb_otg2_dp */
#define BOARD_INITPINS_OTG2_DP_PIN_NAME                              USB_OTG2_DP   /*!< Pin name */
#define BOARD_INITPINS_OTG2_DP_LABEL                                   "OTG2_DP"   /*!< Label */
#define BOARD_INITPINS_OTG2_DP_NAME                                    "OTG2_DP"   /*!< Identifier name */

/* GPIO_AD_B0_11 (coord G10), JTAG_nTRST/J21[3]/INT2_COMBO/LCD_TOUCH_INT/J22[3]/U32[9] */
#define BOARD_INITPINS_INT2_COMBO_PERIPHERAL                                JTAG   /*!< Device name: JTAG */
#define BOARD_INITPINS_INT2_COMBO_SIGNAL                                   TRSTB   /*!< JTAG signal: TRSTB */
#define BOARD_INITPINS_INT2_COMBO_PIN_NAME                         GPIO_AD_B0_11   /*!< Pin name */
#define BOARD_INITPINS_INT2_COMBO_LABEL "JTAG_nTRST/J21[3]/INT2_COMBO/LCD_TOUCH_INT/J22[3]/U32[9]" /*!< Label */
#define BOARD_INITPINS_INT2_COMBO_NAME                              "INT2_COMBO"   /*!< Identifier name */

/* GPIO_AD_B1_09 (coord M13), SAI1_MCLK/CSI_D8/J35[11] */
#define BOARD_INITPINS_CSI_D8_PERIPHERAL                                    SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_CSI_D8_SIGNAL                                    sai_mclk   /*!< SAI1 signal: sai_mclk */
#define BOARD_INITPINS_CSI_D8_PIN_NAME                             GPIO_AD_B1_09   /*!< Pin name */
#define BOARD_INITPINS_CSI_D8_LABEL                   "SAI1_MCLK/CSI_D8/J35[11]"   /*!< Label */
#define BOARD_INITPINS_CSI_D8_NAME                                      "CSI_D8"   /*!< Identifier name */

/* GPIO_AD_B1_11 (coord J13), SAI1_RX_BCLK/CSI_D6/J35[7]/J23[2] */
#define BOARD_INITPINS_CSI_D6_PERIPHERAL                                    SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_CSI_D6_SIGNAL                                 sai_rx_bclk   /*!< SAI1 signal: sai_rx_bclk */
#define BOARD_INITPINS_CSI_D6_PIN_NAME                             GPIO_AD_B1_11   /*!< Pin name */
#define BOARD_INITPINS_CSI_D6_LABEL          "SAI1_RX_BCLK/CSI_D6/J35[7]/J23[2]"   /*!< Label */
#define BOARD_INITPINS_CSI_D6_NAME                                      "CSI_D6"   /*!< Identifier name */

/* GPIO_AD_B1_12 (coord H12), SAI1_RXD/CSI_D5/J35[5]/U13[16] */
#define BOARD_INITPINS_CSI_D5_PERIPHERAL                                    SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_CSI_D5_SIGNAL                                sai_rx_data0   /*!< SAI1 signal: sai_rx_data0 */
#define BOARD_INITPINS_CSI_D5_PIN_NAME                             GPIO_AD_B1_12   /*!< Pin name */
#define BOARD_INITPINS_CSI_D5_LABEL             "SAI1_RXD/CSI_D5/J35[5]/U13[16]"   /*!< Label */
#define BOARD_INITPINS_CSI_D5_NAME                                      "CSI_D5"   /*!< Identifier name */

/* GPIO_AD_B1_10 (coord L13), SAI1_RX_SYNC/CSI_D7/J35[9]/J23[1] */
#define BOARD_INITPINS_CSI_D7_PERIPHERAL                                    SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_CSI_D7_SIGNAL                                 sai_rx_sync   /*!< SAI1 signal: sai_rx_sync */
#define BOARD_INITPINS_CSI_D7_PIN_NAME                             GPIO_AD_B1_10   /*!< Pin name */
#define BOARD_INITPINS_CSI_D7_LABEL          "SAI1_RX_SYNC/CSI_D7/J35[9]/J23[1]"   /*!< Label */
#define BOARD_INITPINS_CSI_D7_NAME                                      "CSI_D7"   /*!< Identifier name */

/* GPIO_AD_B1_14 (coord G12), SAI1_TX_BCLK/CSI_D3/J35[4]/U13[12] */
#define BOARD_INITPINS_CSI_D3_PERIPHERAL                                    SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_CSI_D3_SIGNAL                                 sai_tx_bclk   /*!< SAI1 signal: sai_tx_bclk */
#define BOARD_INITPINS_CSI_D3_PIN_NAME                             GPIO_AD_B1_14   /*!< Pin name */
#define BOARD_INITPINS_CSI_D3_LABEL         "SAI1_TX_BCLK/CSI_D3/J35[4]/U13[12]"   /*!< Label */
#define BOARD_INITPINS_CSI_D3_NAME                                      "CSI_D3"   /*!< Identifier name */

/* GPIO_AD_B1_13 (coord H11), SAI1_TXD/CSI_D4/J35[3]/U13[14] */
#define BOARD_INITPINS_CSI_D4_PERIPHERAL                                    SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_CSI_D4_SIGNAL                                sai_tx_data0   /*!< SAI1 signal: sai_tx_data0 */
#define BOARD_INITPINS_CSI_D4_PIN_NAME                             GPIO_AD_B1_13   /*!< Pin name */
#define BOARD_INITPINS_CSI_D4_LABEL             "SAI1_TXD/CSI_D4/J35[3]/U13[14]"   /*!< Label */
#define BOARD_INITPINS_CSI_D4_NAME                                      "CSI_D4"   /*!< Identifier name */

/* GPIO_AD_B1_15 (coord J14), SAI1_TX_SYNC/CSI_D2/J35[6]/U13[13] */
#define BOARD_INITPINS_CSI_D2_PERIPHERAL                                    SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_CSI_D2_SIGNAL                                 sai_tx_sync   /*!< SAI1 signal: sai_tx_sync */
#define BOARD_INITPINS_CSI_D2_PIN_NAME                             GPIO_AD_B1_15   /*!< Pin name */
#define BOARD_INITPINS_CSI_D2_LABEL         "SAI1_TX_SYNC/CSI_D2/J35[6]/U13[13]"   /*!< Label */
#define BOARD_INITPINS_CSI_D2_NAME                                      "CSI_D2"   /*!< Identifier name */

/* GPIO_AD_B0_10 (coord G13), JTAG_TDO/J21[13]/INT1_COMBO/ENET_INT/J22[6]/U32[11] */
#define BOARD_INITPINS_INT1_COMBO_PERIPHERAL                                SAI2   /*!< Device name: SAI2 */
#define BOARD_INITPINS_INT1_COMBO_SIGNAL                                sai_mclk   /*!< SAI2 signal: sai_mclk */
#define BOARD_INITPINS_INT1_COMBO_PIN_NAME                         GPIO_AD_B0_10   /*!< Pin name */
#define BOARD_INITPINS_INT1_COMBO_LABEL "JTAG_TDO/J21[13]/INT1_COMBO/ENET_INT/J22[6]/U32[11]" /*!< Label */
#define BOARD_INITPINS_INT1_COMBO_NAME                              "INT1_COMBO"   /*!< Identifier name */

/* GPIO_EMC_01 (coord F3), SEMC_D1 */
#define BOARD_INITPINS_SEMC_D1_PERIPHERAL                                   SEMC   /*!< Device name: SEMC */
#define BOARD_INITPINS_SEMC_D1_SIGNAL                                       DATA   /*!< SEMC signal: DATA */
#define BOARD_INITPINS_SEMC_D1_CHANNEL                                        1U   /*!< SEMC DATA channel: 01 */
#define BOARD_INITPINS_SEMC_D1_PIN_NAME                              GPIO_EMC_01   /*!< Pin name */
#define BOARD_INITPINS_SEMC_D1_LABEL                                   "SEMC_D1"   /*!< Label */
#define BOARD_INITPINS_SEMC_D1_NAME                                    "SEMC_D1"   /*!< Identifier name */

/* GPIO_B0_12 (coord C10), LCDIF_D8/BT_CFG[8] */
#define BOARD_INITPINS_LCDIF_D8_PERIPHERAL                                  SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_LCDIF_D8_SIGNAL                              sai_tx_data1   /*!< SAI1 signal: sai_tx_data1 */
#define BOARD_INITPINS_LCDIF_D8_PIN_NAME                              GPIO_B0_12   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_D8_LABEL                       "LCDIF_D8/BT_CFG[8]"   /*!< Label */
#define BOARD_INITPINS_LCDIF_D8_NAME                                  "LCDIF_D8"   /*!< Identifier name */

/* GPIO_B0_11 (coord A10), LCDIF_D7/BT_CFG[7] */
#define BOARD_INITPINS_LCDIF_D7_PERIPHERAL                                  SAI1   /*!< Device name: SAI1 */
#define BOARD_INITPINS_LCDIF_D7_SIGNAL                              sai_tx_data2   /*!< SAI1 signal: sai_tx_data2 */
#define BOARD_INITPINS_LCDIF_D7_PIN_NAME                              GPIO_B0_11   /*!< Pin name */
#define BOARD_INITPINS_LCDIF_D7_LABEL                       "LCDIF_D7/BT_CFG[7]"   /*!< Label */
#define BOARD_INITPINS_LCDIF_D7_NAME                                  "LCDIF_D7"   /*!< Identifier name */

#define PINMUX_KEYBOARD_SCL         IOMUXC_GPIO_B0_04_LPI2C2_SCL
#define PINMUX_KEYBOARD_SDA         IOMUXC_GPIO_B0_05_LPI2C2_SDA
#define PINMUX_KEYBOARD_RESET       IOMUXC_GPIO_B1_13_GPIO2_IO29
#define PINMUX_KEYBOARD_IRQ         IOMUXC_GPIO_B1_12_GPIO2_IO28

#define PINMUX_POWER_SW						IOMUXC_GPIO_B0_06_GPIO2_IO06
#define PINMUX_POWER_HOLD					IOMUXC_GPIO_B0_07_GPIO2_IO07

#define PINMUX_CELLULAR_PWRKEY            IOMUXC_GPIO_B1_02_GPIO2_IO18
#define PINMUX_CELLULAR_RESET             IOMUXC_GPIO_B1_01_GPIO2_IO17
#define PINMUX_CELLULAR_SIM_TRAY_INSERTED IOMUXC_GPIO_B0_11_GPIO2_IO11
#define PINMUX_CELLULAR_SIM_PRESENCE      IOMUXC_GPIO_B0_09_GPIO2_IO09
#define PINMUX_CELLULAR_ANTENNA_SELECT    IOMUXC_GPIO_B0_02_GPIO2_IO02
#define PINMUX_CELLULAR_STATUS            IOMUXC_GPIO_AD_B0_02_GPIO1_IO02
#define PINMUX_CELLULAR_USB_BOOT_PIN      IOMUXC_GPIO_B1_08_GPIO2_IO24
#define PINMUX_CELLULAR_WAKEUP_IN         IOMUXC_GPIO_B1_03_GPIO2_IO19
#define PINMUX_CELLULAR_DTR               IOMUXC_GPIO_EMC_41_GPIO3_IO27


#define PINMUX_USB_FUNCTION_MUX_SELECT    IOMUXC_GPIO_AD_B1_09_GPIO1_IO25

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
