#pragma once

#include <stdbool.h>

//! Handle structure for the SRK configuration
struct program_keys_handle {
    char *srk_file;        //! SRK key file
    char *chksum_srk_file; //! SRK key md5sum generated by md5sum utility
};

//! Error codes returned by the program keys
enum program_keys_errors {
    error_pgm_keys_ok,                     //! Checksum OK
    error_pgm_keys_vfs,                    //! VFS internal error
    error_pgm_keys_no_srk_file,            //! No srk file on the FS
    error_pgm_keys_no_sum_file,            //! No checksum file on the FS
    error_pgm_keys_srk_key_size_error,     //! SRK files length error
    error_pgm_keys_chksum_file_size_error, //! Checksum file length error
    error_pgm_keys_chksum_content_error,   //! Checksum content error
    error_pgm_keys_mismatch_checksum,      //! Checksum mismatch
    error_pgm_keys_mismatch_filename,      //! Mismatch filename
    error_pgm_keys_already_programmed,     //! Keys already programmed cfg is closed
    error_pgm_keys_pgm_fail,               //! Programming keys fail
    error_pgm_keys_efuse_verify            //! Efuse verify error
};

/** Program security keys HAB 
 * The function searches SRK_fuses.bin
 * and SRK_fuses.bin.md5 in the base directory
 * @param[in] pgm_handle Handle for key programming
 * @param[in] tl Trace logger object
 */
int program_keys(const struct program_keys_handle *pgm_handle);

/** Return true when programming keys is needed
 * @param[in] pgm_handle Key programming config structure
 * @return Error code on success
 */
bool program_keys_is_needed(const struct program_keys_handle *pgm_handle);
