#pragma once

#include <common/trace.h>

//! Handle structure for the SRK configuration
struct program_keys_handle
{
    const char *srk_file;        //! SRK key file
    const char *chksum_srk_file; //! SRK key md5sum generated by md5sum utility
};

//! Error codes returned by the program keys
enum program_keys_errors
{
    error_pgm_keys_ok,                     //! Checksum OK
    error_pgm_keys_vfs,                    //! VFS internal error
    error_pgm_keys_no_srk_file,            //! No srk file on the FS
    error_pgm_keys_no_sum_file,            //! No checksum file on the FS
    error_pgm_keys_srk_key_size_error,     //! SRK files length error
    error_pgm_keys_chksum_file_size_error, //! Checksum file length error
    error_pgm_keys_chksum_content_error,   //! Checksum content error
    error_pgk_keys_mismatch_checksum       //! Checksum mismatch
};

/** Program security keys HAB 
 * The function searches SRK_fuses.bin
 * and SRK_fuses.bin.md5 in the base directory
 * @param[in] pgm_handle Handle for key programming
 * @param[in] tl Trace logger object
 */
int program_keys(const struct program_keys_handle *pgm_handle, trace_list_t *tl);
